### ISSUE TITLE
Missing modules yaml and base-addon?

### ISSUE THREAD

**Issue by TRR-Slimer** [Spicord/ChatSync#1]
when i start the code it stops here

```
const BaseAddon = require('base-addon')
```
and gives the error:

> Error: Cannot find module 'base-addon'
Require stack:
- C:\Users\FiercePC\Downloads\ChatSync-master\ChatSync-master\src\ChatSyncAddon.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\FiercePC\Downloads\ChatSync-master\ChatSync-master\src\ChatSyncAddon.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\FiercePC\\Downloads\\ChatSync-master\\ChatSync-master\\src\\ChatSyncAddon.js'

any help would be appreciated and i understand it has been 3 months since this code was last updated

**Comment by OopsieWoopsie** [comment]
That's not supposed to work in NodeJS...

**Comment by TRR-Slimer** [comment]
thats what i realised when i closed it :/
